### ISSUE TITLE
enable by default?

### ISSUE THREAD

**Issue by mdering** [yitzchak/linter-spell-latex#19]
Would it be possible to enable this for any .tex file, for example, rather than requiring a magic command?

**Comment by yitzchak** [comment]
A magic comment should not be required to enable. It is only used to override the language on a per document basis.

**Comment by mdering** [comment]
Do you have any idea why this behavior might be happening then? I’m not
familiar enough with atom debugging to attach anything useful, but it only
works when i add a magic comment
--
Matt

On December 8, 2016 at 12:23:58 PM, Tarn Burton (notifications@github.com)
wrote:

A magic comment should not be required to enable. It is only used to
override the language on a per document basis.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yitzchak/linter-spell-latex/issues/19#issuecomment-265799725>,
or mute the thread

**Comment by mdering** [comment]
I believe setting my default language in linter-spell fixed it.
