### ISSUE TITLE
Don't spell check citation keys

### ISSUE THREAD

**Issue by grulg** [yitzchak/linter-spell-latex#8]
When citing other papers, the spell checker picks up on the citation keys and tries to correct them. It racks up a lot of annoying warnings. See picture.

![screen shot 2016-07-26 at 16 40 04](https://cloud.githubusercontent.com/assets/2463336/17304858/ba232fc2-57f5-11e6-9026-d3cfef5abd08.png)

In this case, it suggests that "Dourish2004" should be "Nourished". I would like the spell checker to just skip these kinds of suggestions.

**Comment by yitzchak** [comment]
Just pushed out a patch since think this got fixed in 396f81647cd7da4624ad0144e124bc074f459ba6

**Comment by yitzchak** [comment]
Please try updating to 0.7.1

**Comment by grulg** [comment]
That did it! Thanks for the fast update.

On a related note: Comments are also spell checked. I usually write todos to myself, something like `% TODO Baltrunas' ideas should be explored further.` The spell checker then complains on the words "TODO" and "Baltrunas'" (which is a surname). I see the point in spell checking comments, but in this case it also kind of annoying. Maybe one should be able to turn spell checking for comments on and off? I can make another issue out of this, if you want.

**Comment by yitzchak** [comment]
I agree that the spell checking in comments is an issue. I haven't figured out the best way to resolve it yet.

Please create a new issue and I'll start working on some ideas.
