### ISSUE TITLE
Spell checking of comments

### ISSUE THREAD

**Issue by grulg** [yitzchak/linter-spell-latex#9]
I usually write todos to myself, something like 

```
% TODO Baltrunas' ideas should be explored further.
```

 The spell checker then complains on the words "TODO" and "Baltrunas'" (which is a surname). I see the point in spell checking comments, but in this case it also kind of annoying. Maybe one should be able to turn spell checking for comments on and off?

**Comment by yitzchak** [comment]
Do you have `language-todo` enabled?

**Comment by grulg** [comment]
Yes, not entirely sure what it does though. From what I can tell by disabling/enabling, it seems like it only highlights the "TODO" part.

**Comment by yitzchak** [comment]
You are correct, it just highlights TODO and various other keywords in comments. I added the scopes that used by `language-todo` to `linter-spell` in fa6073efe4b6ff5124f7e1934bd5565249f38f6f so at least those will not be spell checked. I'll push out a patch release in a bit.

**Comment by yitzchak** [comment]
The patch to ignore `language-todo` scopes just got pushed out in `linter-spell` v0.9.2 

I am still thinking about how to make spell checking in comments a configuration option.

**Comment by yitzchak** [comment]
Added a configuration option to control spell checking in comments. You will need to upgrade to `linter-spell` v0.10.0 and `linter-spell-latex` v0.8.0

**Comment by grulg** [comment]
I think that will solve this issue for most users.

Awesome work, keep it up!
